# Here you can configure your own Continuous Integration script
# Maybe create a registry image with the back-end already installed

stages:
  - some_stage

some_job:
  stage: some_stage
  script:
    # install the wrapper and an ontology if needed
    - install_some_things
    - run_other_things
    - testing_and_coverage_too
